export const projectsData = [
    {
        clientName: "alex",
        developers: [
            { developerName: "arslan" },
            { developerName: "ali" },
            { developerName: "ahmad" },
            { developerName: "arslan" },
            { developerName: "ali" },
            { developerName: "ahmad" },
        ],
        isCompleted: false,
        projectName: "AEI",
        projectDescription: "housing project",
        _id: 1,
    },
    {
        clientName: "alex",
        developers: [{ developerName: "arslan" }],
        isCompleted: true,
        projectName: "AEI",
        projectDescription: "housing project",
        _id: 1,
    },
    {
        clientName: "alex",
        developers: [{ developerName: "arslan" }],
        isCompleted: false,
        projectName: "AEI",
        projectDescription: "housing project",
        _id: 1,
    },
    {
        clientName: "alex",
        developers: [
            { developerName: "arslan" },
            { developerName: "ali" },
            { developerName: "ahmad" },
            { developerName: "arslan" },
            { developerName: "ali" },
            { developerName: "ahmad" },
        ],
        isCompleted: false,
        projectName: "AEI",
        projectDescription: "housing project",
        _id: 1,
    },
    {
        clientName: "alex",
        developers: [{ developerName: "arslan" }],
        isCompleted: true,
        projectName: "AEI",
        projectDescription: "housing project",
        _id: 1,
    },
    {
        clientName: "alex",
        developers: [{ developerName: "arslan" }],
        isCompleted: false,
        projectName: "AEI",
        projectDescription: "housing project",
        _id: 1,
    },
]